# Generated by Django 4.2.5 on 2023-09-16 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testwronganswers',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TestWrongAnswers_Answer', to='api.answertest'),
        ),
        migrations.AlterField(
            model_name='testwronganswers',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TestWrongAnswers_Question', to='api.questiontest'),
        ),
    ]
