# Generated by Django 4.2.5 on 2023-09-18 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_choice_hm_questions_remove_answertest_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HMAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='hm',
            name='is_test',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='hm',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_hm', to='api.hm'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_quesion', to='api.questions'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='hm',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_hm', to='api.hm'),
        ),
        migrations.CreateModel(
            name='HMWrongAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrong_answer_choice', to='api.choice')),
                ('hm', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrong_answer_hm', to='api.hm')),
                ('hm_answer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrong_answer_hm_answer', to='api.hmanswer')),
                ('question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrong_answer_quesion', to='api.questions')),
            ],
        ),
        migrations.AddField(
            model_name='hmanswer',
            name='choice',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_choice', to='api.choice'),
        ),
        migrations.AddField(
            model_name='hmanswer',
            name='hm',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_hm', to='api.hm'),
        ),
        migrations.AddField(
            model_name='hmanswer',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_quesion', to='api.questions'),
        ),
        migrations.AddField(
            model_name='hmanswer',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_student', to='api.student'),
        ),
    ]
