# Generated by Django 4.2.5 on 2023-09-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_hmanswer_hm_is_test_alter_choice_hm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hmanswer',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='hmanswer',
            name='question',
        ),
    ]
