# Generated by Django 4.2.5 on 2023-09-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_hmanswer_choice_remove_hmanswer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hmwronganswer',
            name='hm',
        ),
    ]
