# Generated by Django 4.2.5 on 2023-09-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_hmwronganswer_hm'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmanswer',
            name='review',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
