# Generated by Django 4.2.5 on 2023-09-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_hmanswer_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='HMDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default=False, max_length=255, null=True)),
                ('choice1', models.CharField(blank=True, default=False, max_length=255, null=True)),
                ('choice2', models.CharField(blank=True, default=False, max_length=255, null=True)),
                ('choice3', models.CharField(blank=True, default=False, max_length=255, null=True)),
                ('correct_choice', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('hm', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.hm')),
            ],
        ),
        migrations.RemoveField(
            model_name='hmanswer',
            name='hm',
        ),
        migrations.RemoveField(
            model_name='hmanswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='hmwronganswer',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='hmwronganswer',
            name='hm_answer',
        ),
        migrations.RemoveField(
            model_name='hmwronganswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='hm',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='HMAnswer',
        ),
        migrations.DeleteModel(
            name='HMWrongAnswer',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
