# Generated by Django 4.2.5 on 2023-09-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_hmdetails_remove_hmanswer_hm_remove_hmanswer_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hmdetails',
            name='created_at',
        ),
    ]
