# Generated by Django 4.2.5 on 2023-09-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_hmdetails_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmdetails',
            name='choice1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hmdetails',
            name='choice2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hmdetails',
            name='choice3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hmdetails',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
