# Generated by Django 4.2.5 on 2023-09-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_homework_answeredquestion_date_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_answer', to='api.homework'),
        ),
        migrations.AddField(
            model_name='question',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_question', to='api.homework'),
        ),
    ]
