# Generated by Django 4.2.5 on 2023-09-18 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_homework_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeredquestion',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answered', to='api.homework'),
        ),
    ]
