# Generated by Django 4.2.5 on 2023-09-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_answeredquestion_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeredquestion',
            name='homework',
        ),
        migrations.RemoveField(
            model_name='answeredquestion',
            name='student',
        ),
        migrations.CreateModel(
            name='AnswerdQuestionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, max_length=200, null=True)),
                ('homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answered', to='api.homework')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answered', to='api.student')),
            ],
        ),
        migrations.AddField(
            model_name='answeredquestion',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details_answered', to='api.answerdquestiondetails'),
        ),
    ]
