# Generated by Django 4.2.5 on 2023-09-19 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeredquestion',
            name='correct_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer_answered', to='api.answer'),
        ),
    ]
