# Generated by Django 4.2.5 on 2023-09-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
