# Generated by Django 4.2.5 on 2023-09-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='review',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
