# Generated by Django 4.2.5 on 2023-09-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_student_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='review',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
    ]
