# Generated by Django 4.2.5 on 2023-09-19 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_student_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='review',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
